### ISSUE TITLE
Include file xms_content\unitvariables\BlackOutSystem/state.hpp not found

### ISSUE THREAD

**Issue by gersh99** [X39/Project-Alcatraz#3]
Used Mods
=========
@ Project Alcatraz 

Steps to reproduce
==================
1. Friend me on steam for access to most current private build, 
2. Start game
3. Error on addon initialization 

Issues
======
* While step 2: that and that is happening

Expected
========
* While step 2: that and that should happen

Additional Notes
================
This fault on addon initialization in contrast to the previous bug which got past loading to black screen
![problem2](https://user-images.githubusercontent.com/22155572/55685929-67b5a700-5929-11e9-868c-75f63ac4fa14.PNG)

**Comment by gersh99** [comment]
Notably this path actually exists.

**Comment by X39** [comment]
regardless of what the private content is, this is no bug to fix.

the include path is indeed wrong, due to $PBO_PREFIX$ existing
https://github.com/X39/Project-Alcatraz/blob/master/xms_content/%24PBOPREFIX%24
`x\xms\extensivemedicalsystem\content`

the correct path for the include thus would be: `x\xms\extensivemedicalsystem\content\UnitVariables\BlackOutSystem\state.hpp`

**Comment by X39** [comment]
Closing (stale), assuming fixed.
Feel free to reopen if not.
